defaultSemverRangePrefix: ""

enableGlobalCache: true

enableProgressBars: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.2.0.cjs
